//-------------------------------------------------------------------
//
//  This code is copyright 2007 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//
//-------------------------------------------------------------------
// #########################################################################################
//                                       HE bullet in ground detonation
// #########################################################################################
// =======================================================================================
class CHE7576_85_88BulletGroundHitEffect
  extends CBaseEffect
{
  CHE7576_85_88BulletGroundHitEffect()
  {
    CreateEffect("LightExplosionSplash",         0.0);
    CreateEffect("HEGroundSplashRefuseEffect",   0.0);
    CreateEffect("HEGroundDustRefuseEffect",     0.1);
    CreateEffect("HEGroundDustSinkRefuseEffect", 0.0);
    CreateEffect("HEGroundSmokeRefuseEffect",    0.1);
    CreateEffect("HEGroundSprayRefuseEffect",    0.0);
    CreateAndForgetEffect("HE7576_85_88GroundSignEffect", 0.0);
  }
}
// ==================================================== Splash  ==========================
  class CHE7576_85_88BulletBodyHitEffect
  extends CBaseEffect
{
  CHE7576_85_88BulletBodyHitEffect()
  {
    CreateEffect("LightExplosionSplash",         0.0);
    CreateEffect("HEGroundSplashRefuseEffect",   0.0);
    CreateEffect("HEGroundDustRefuseEffect",     0.1);
    CreateEffect("HEGroundDustSinkRefuseEffect", 0.0);
    CreateEffect("HEGroundSmokeRefuseEffect",    0.1);
    CreateEffect("HEGroundSprayRefuseEffect",    0.0);

  }
}

class CHEGroundSplashRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ...............................................................................
   float EjectionPeriodMS   = 0.01;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.0;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.05;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 4.0;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 1.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.7;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = -1.0;   	//рандомизация смещени

   int ThetaMin             = 0;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 30;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_fire1.tex";	//имя файла текстуры

   boolean UseInvAlpha      = false;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 256;     	//размер кадра по ширине
   int     TexFrameY        = 256;     	//размер кадра по высоте

   String ParticlesClass    = "CHEGroundSplashRefuseParticle";    //имя описателя частиц

// Data block ...............................................................................
CHEGroundSplashRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEGroundSplashRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 0.04;  		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 0.05;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 0.5;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 1.0;		//коэффициент наследования начальной
									//  скорости эмитеера
   float ConstantAcceleration       = -1.0;		//собственное усокрение

   float SpinRandomMin              = -3.0;		//мин поворот частицы вокруг
									//  своей нормали(-3.14 до 3.14)
   float SpinRandomMax              =  3.0;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.1;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.4, 1.0];				//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
                    new Color(0.5, 0.5, 0.5, 0.6),
                    new Color(0.5, 0.5, 0.5, 0.8),
                    new Color(0.5, 0.5, 0.5, 0.0)
                  ];

   Array sizes  = [0.3, 4.0, 2.0];				//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
					[0],
					[0]
                  ];
// Data block ..............................................................................
}
// ===================================================  Dust   ==========================
class CHEGroundDustRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ...............................................................................
   float EjectionPeriodMS   = 0.005;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.001;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.06;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 6.0;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 5.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 1.0;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = 0.0;   	//рандомизация смещени

   int ThetaMin             = 0;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 30;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_test4.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 256;     	//размер кадра по ширине
   int     TexFrameY        = 256;     	//размер кадра по высоте

   String ParticlesClass    = "CHEGroundDustRefuseParticle";    //имя описателя частиц

// Data block ...............................................................................
CHEGroundDustRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ --------------------------------------------------------------------------
class CHEGroundDustRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ..............................................................................
   float ParticleLifetimeMS         = 2.0;  		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 1.0;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 1.0;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 1.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = -0.5;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									// своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.001;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.1, 0.7, 1.0];			//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
                    new Color(0.2, 0.2, 0.1, 0.3),
                    new Color(0.4, 0.39, 0.25, 0.4),
                    new Color(0.4, 0.39, 0.20, 0.4),
                    new Color(0.7, 0.69, 0.45, 0.4)
                  ];

   Array sizes  = [0.3, 1.0, 2.0, 3.0];			//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
					[0],
					[0],
					[0]
                  ];
// Data block ..............................................................................
}
// ================================================ Dust Sink ==============================
class CHEGroundDustSinkRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ...............................................................................
   float EjectionPeriodMS   = 0.001;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.00;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.2;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 2.0;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 0.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.0;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = -0.3;   	//рандомизация смещени

   int ThetaMin             = 90;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 92;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_test3.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 64;     	//размер кадра по ширине
   int     TexFrameY        = 64;     	//размер кадра по высоте

   String ParticlesClass    = "CHEGroundDustSinkRefuseParticle";    //имя описателя частиц

// Data block .............................................................................
CHEGroundDustSinkRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEGroundDustSinkRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 1.0; 		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 4.0;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 0.02;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 0.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = 0.1;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									//  своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.1;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.05, 0.08, 0.12, 0.5, 0.7, 1.0];	//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
 				new Color(0.5, 0.5, 0.45, 0.0),
 				new Color(0.5, 0.5, 0.45, 0.1),
				new Color(0.5, 0.5, 0.45, 0.2),
                    	new Color(0.5, 0.5, 0.45, 0.0),
                    	new Color(0.5, 0.5, 0.45, 0.5),
				new Color(0.5, 0.5, 0.45, 0.2),
                  	new Color(0.5, 0.5, 0.45, 0.0)
                  ];

   Array sizes  = [0.1, 1.0, 0.2, 0.4, 0.6, 1.3, 3.0];		//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
					[9],
					[9],
					[9],
					[9],
					[9],
					[9]
                  ];
// Data block ..............................................................................
}
// ================================================ Smoke ==================================
class CHEGroundSmokeRefuseEffect
  extends CBaseRefuseEffect
{
// Data block .............................................................................
   float EjectionPeriodMS   = 0.004;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.005;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.03;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 0.6;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 4.0;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.5;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = -1.0;   	//рандомизация смещени

   int ThetaMin             = 0;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 25;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = true; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Eff_test3.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 256;     	//размер кадра по ширине
   int     TexFrameY        = 256;     	//размер кадра по высоте

   String ParticlesClass    = "CHEGroundSmokeRefuseParticle";    //имя описателя частиц

// Data block .............................................................................
CHEGroundSmokeRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEGroundSmokeRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 2.0; 		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 9.0;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = -0.02;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 0.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = -0.3;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									//  своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.09;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.05, 0.1, 0.3, 1.0];		//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
 		        new Color(1.0, 1.0, 1.0, 0.1),
                    new Color(0.5, 0.5, 0.5, 0.7),
                    new Color(0.6, 0.6, 0.6, 0.6),
                    new Color(0.5, 0.5, 0.4, 0.2),
                    new Color(0.0, 0.0, 0.0, 0.0)
                  ];

   Array sizes  = [0.1, 0.5, 1.5, 4.0, 15.0];		//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
			  [0],
			  [0],
			  [0],
			  [0]
                  ];
// Data block ..............................................................................
}
// ================================================ Spray ==================================
class CHEGroundSprayRefuseEffect
  extends CBaseRefuseEffect
{
// Data block ..............................................................................
   float EjectionPeriodMS   = 0.005;	//период генерации частицы, (сек)
   float PeriodVarianceMS   = 0.001;   	//рандомизация периода (сек)
   float LifetimeMS         = 0.1;   	//время жизни эмитеера (время выброса частиц, с)
   float EjectionVelocity   = 10.5;   	//начальная скорость частицы (м/с)
   float VelocityVariance   = 3.5;   	//рандомизация начальной скорости (м/с)
   float EjectionOffsetMin  = 0.0;   	//мин радиус эмитеера в нормальной плоскости (м)
   float EjectionOffsetMax  = 0.0;   	//макс радиус эмитеера в нормальной плоскости (м)
   float ShiftVariance      = 0.0;   	//смещение вдоль вектора начальной скорости (м)
   float Shift              = -1.1;   	//рандомизация смещени

   int ThetaMin             = 0;    	//мин отклонение скорости частицы от норм эмиттера
   int ThetaMax             = 15;    	//макс отклонение
   int PhiReferenceVel      = 0;     	//начало сектора генерации в норм плоскости (град)
   int PhiVariance          = 360;   	//конец сектора генерации в  (град, 0-360 -круг)
   boolean OverrideAdvances = false; 	//использование частицами локала эмитеера
							//  (true-да, false - нет)
   boolean OrientParticles  = true;  	//ориентация нормалей частиц "на камеру"
							//  (true-да, false - нет)
   boolean m_LightingParticle = false; 	//освещенность патиклов (true-да, false - нет)
   float m_LightingInterpolate = 0.5;  	//смещение серого к свету (0-1)

   String TexName           = "textures/Effect_7.tex";	//имя файла текстуры

   boolean UseInvAlpha      = true;  	//тип прозрачности false - аддитивная,
							//  true - нормальна
   int     TexSize          = 256;    	//размер текстуры в пикселах
   int     TexFrameX        = 64;     	//размер кадра по ширине
   int     TexFrameY        = 64;     	//размер кадра по высоте

   String ParticlesClass    = "CHEGroundSprayRefuseParticle";    //имя описателя частиц

// Data block .............................................................................
CHEGroundSprayRefuseEffect()
   {
     String Transparency = "NORMAL";
     if(!UseInvAlpha)
       Transparency = "ADDITIVE";
     CBaseRefuseEffectSkin::TexName = TexName;
     CBaseRefuseEffectSkin::Transparency = Transparency;
     CBaseRefuseEffectSkin::Size = TexSize;
     CBaseRefuseEffectSkin::XSize = TexFrameX;
     CBaseRefuseEffectSkin::YSize = TexFrameY;
     CBaseRefuseEffect::Init();
   }
}
// ОПИСАНИЕ ЧАСТИЦ ------------------------------------------------------------------------
class CHEGroundSprayRefuseParticle
  extends CBaseRefuseParticle
{
// Data block ............................................................................
   float ParticleLifetimeMS         = 0.05; 		//время жизни частицы (сек)
   float ParticleLifetimeVarianceMS = 0.5;		//вариация времени жизни(сек)
   float DragCoefficient            = 1.0;		//not in use
   float GravityCoefficient         = 0.6;		//коэффициент влияния гравитации
   float InheritedVelFactor         = 1.0;		//коэффициент наследования начальной
									// скорости эмитеера
   float ConstantAcceleration       = -1.1;		//собственное усокрение

   float SpinRandomMin              = -3.1;		//мин поворот частицы вокруг
									//  своей нормали (-3.14 до 3.14)
   float SpinRandomMax              =  3.1;		//макс (-3.14 до 3.14)
   float SpinSpeed                  =  0.05;		//скорость вращени

//БЛОК ДИНАМИКИ ---------------------------------------------------------------------------
  Array times  = [0.0, 0.1, 0.4, 1.0];			//временные периоды в течение
									// жизни частицы (до 8 периодов)

  Array colors = [ 						//цвет и альфа частицы по периодам
                    new Color(0.9, 0.9, 0.9, 0.1),
                    new Color(0.9, 0.9, 0.9, 0.7),
                    new Color(0.9, 0.9, 0.9, 0.1),
                    new Color(0.9, 0.9, 0.9, 0.0)
                  ];

   Array sizes  = [0.1, 0.5, 1.5, 4.5];			//размер частицы по периодам (масштаб)

   Array frames = [                           		//кадры анимации между периодами
                    [7],
			  [7],
			  [7]
                  ];
// Data block ..............................................................................
}