//-------------------------------------------------------------------
//
//  This code is copyright 2001 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//  Redux Added missing Models
//-------------------------------------------------------------------

class CPlanarShadows
{
  static void InitializePlanarShadows()
  {
  
//Buildings   
   //Cbld_BarrackModel::PlanarShadow           = true;
    Cbld_BarricadeModel::PlanarShadow          = true;	
    Cbld_Barricade_PakModel::PlanarShadow      = true;
	Cbld_BridgeWoodModel::PlanarShadow         = true;
    Cbld_DotConcreteModel::PlanarShadow        = true;
    Cbld_DzotWoodModel::PlanarShadow           = true; 
    Cbld_HaystackModel::PlanarShadow           = true;
    Cbld_PileLogsModel::PlanarShadow           = true;
    Cbld_PostElectricModel::PlanarShadow       = true;
    Cbld_PostSpeakerModel::PlanarShadow        = true;	
	Cbld_ReloadGerModel::PlanarShadow          = true;
	Cbld_ReloadUSSRModel::PlanarShadow         = true;
    Cbld_SandBagWallModel::PlanarShadow        = true;	
	Cbld_USRCorralWoodModel::PlanarShadow      = true;
    Cbld_USRHouseWoodModel::PlanarShadow       = true;
    Cbld_USRShedWoodModel::PlanarShadow        = true;
    Cbld_USRShedWood02Model::PlanarShadow      = true;
    Cbld_WaterWell_2Model::PlanarShadow        = true;
    Cbld_WaterWell_1Model::PlanarShadow        = true;
	
//Fences
    Cfence_WickerModel::PlanarShadow            = true;
    Cfence_PoleModel::PlanarShadow              = true;
    Cfence_PalisadeModel::PlanarShadow          = true;
	
//Environment	
    Cenv_Antitank_singleModel::PlanarShadow     = true;
    Cenv_BarrelModel::PlanarShadow              = true;	
    Cenv_BarrelPackAModel::PlanarShadow         = true;
	Cenv_BarrelPackBModel::PlanarShadow         = true;
    Cenv_WeaponBoxSmallModel::PlanarShadow      = true;

//Human Units	
    Chum_GermanSoldierRifleModel::PlanarShadow  = true;
    Chum_GermanTankmanModel::PlanarShadow       = true;
    Chum_SovietSoldierRifleModel::PlanarShadow  = true;
    Chum_SovietTankmanModel::PlanarShadow       = true;

//Air	
	Cu_air_FW_190Model::PlanarShadow            = true;
    Cu_air_IL2Model::PlanarShadow               = true;
    Cu_air_IL2MModel::PlanarShadow              = true;
	
//Static Guns
	Cu_stat_NebelwerferModel::PlanarShadow      = true;
    Cu_stat_pak40Model::PlanarShadow            = true;
    Cu_stat_zis3Model::PlanarShadow             = true;

//Halftracks	
    Cu_veh_Hanomag_251CModel::PlanarShadow      = true;
    Cu_veh_M3A1HalfTrackModel::PlanarShadow     = true;

//Trucks	
    Cu_veh_OpelBlitzModel::PlanarShadow         = true;
    Cu_veh_zis5Model::PlanarShadow              = true;

//Tanks	
    Cu_veh_PzIVGModel::PlanarShadow             = true;
    Cu_veh_PzVI_MAINModel::PlanarShadow         = true;
	Cu_veh_PzVI_LATEModel::PlanarShadow         = true;
    Cu_veh_t34_76_41Model::PlanarShadow         = true;
	Cu_veh_t34_76_42Model::PlanarShadow         = true;
    Cu_veh_t34_85_44Model::PlanarShadow         = true;
	Cu_veh_SAU_Stug40Model::PlanarShadow        = true;
    Cu_veh_SU85Model::PlanarShadow              = true;  

//Weapons	
     Cwpn_BombModel::PlanarShadow              = true;	
     Cwpn_FFARModel::PlanarShadow              = true; 


	
  }
}
