//-------------------------------------------------------------------
//
//  This code is copyright 2001 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//
//-------------------------------------------------------------------

class CSteppeQuickMissionMission extends CSPMission
{
  //
  // Contruction and initialization
  //

  String  m_LocalTime       = "14:20:00";
  String m_TerrainMapTextureName = "Textures/C1M3_Map.tex";

  static String m_MissionBriefingPicMaterial = "C1M3BriefingPic";

  Array  m_MissionObjectives = [
          ];

  boolean isDebug = true;

  Array m_NavpointsForPlayerMap = [

  ];

  float  CockpitMapMinRange  = 2000.0;
  float  CockpitMapMaxRange  = 9000.0;
  int    CockpitMapZoomSteps = 10;
  Vector MarksInitPoint      = new Vector(2000.0, 2000.0, 0.0);
  float  CockpitMapNavNameMaxRange  = 4000.0;
  Array  CockpitMapAccessBox  = [ new Vector(5484, 3550.0, 0.0), new Vector(14484.0, 12550.0, 0.0)];

  final static Array RouterWorkingZones = [
    ];

  final static Array   DefaultMask = [["ENEMY", "MainMesh"], ["NEUTRAL"]];
  final static Array          Mask = [["ENEMY", "MainMesh"], ["NEUTRAL", "InvisibleOnRadar"]];



  boolean OnTarg = false;
  boolean TigerAggr = false;

  boolean MainPlayerStart = false;

  void CSteppeQuickMissionMission()
  {
    // Construct mission
    CSPMission("CSteppeQuickMissionMission", "SteppeQuickMissionContent");

    // Set mission properties
    SetMissionTerrain(new #ChunkedTerrain<CSteppeQuickMissionTerrain>());
    SetMissionAtmosphere(new #Atmosphere<SteppeQuickMissionAtmosphere>());
    SetMissionSky(new #SkyObject<CSkyModel>());

    if (CDebugSettings::LoadForest)
      SetMissionForest(new CSTBaseForestC1(GetMissionAtmosphere()));
    if (CDebugSettings::LoadRoads)
      SetMissionRoadsParms(new CBaseRoadC1());
    if (CDebugSettings::LoadGrass)
      RegisterObject("Grass", new #Grass<CBaseGrassC1>());


    SetMissionWorldMatrices(new #WorldMatrices<SteppeQuickMissionWorldMatrices>(), [
        [ LAYER_TERRAIN_NAME, "SteppeQuickMissionLandscapeLayer"   ],
        [ LAYER_TERRAIN_ZONE, "SteppeQuickMissionTerrainZoneLayer" ],
        [ LAYER_ROUTER_ZONE,  "SteppeQuickMissionRouterZoneLayer"     ],
        [ LAYER_MICROTEXTURE_MAP1, "SteppeQuickMissionMicroTextures1" ],
        [ LAYER_TERRAIN_WATERHEIGHTS, "SteppeQuickMissionWaterHeights"]
      ]);

    SetRouterPrecalculatedGraph(
      new #RouterPrecalculatedGraph<CRouterPrecalculatedGraph>());

    SetRouterMap("RouterMap_Layer1", new #RouterMap<CBaseRouterMap>(), 64, RouterWorkingZones);
  }

// TODO

  String GetMainRadioHomePoint()
  {
    return "";
  }

  void StartMission()
  {
    // call inherited
    CSPMission::StartMission();

   Component console = new #GameController().GetObject(SOID_Console);
//   console.disablebeh();
   //console.showbehinf(true);

  }

  void OnObjectEnterNavPoint(String _NavPointID, String _ObjectID)
  {
    if (_ObjectID == "MainPlayerUnit")
    {
      sendEvent(1.0, getIdentificator(this), "CloseMission", [MOSID_Completed]);
    }
  }

  void OnObjectLeaveNavPoint(String _NavPointID, String _ObjectID)
  {
  }


  void Shutdown()
  {

    CSPMission::Shutdown();
  }
 }
