//-------------------------------------------------------------------
//
//  This code is copyright 2004 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//
//-------------------------------------------------------------------

class CEditorCursor
  extends CBaseSysObject
{
  final static Array  SysEffects = [ 
                                     "EditorCursorDirection", 
                                     "EditorCursorBounds"        
                                   ];
  final static Array  EffectsSrc = [ 
                                     "CEditorCursorDirectionEffect", 
                                     "CEditorCursorBoundsEffect"     
                                   ];

  CEditorCursor()
  {
    m_Boundings[1] = new Vector(0.1, 0.1, 0.1);

    // Initially disabled
    Enable(false);
  }

  void Enable(
      boolean _IsEnabled
    )
  {
    if (_IsEnabled)
      Show();
    else
      Hide();
  }
}


