//-------------------------------------------------------------------
//                                                                   
//  This code is copyright 2001 by G5 Software.                      
//  Any unauthorized usage, either in part or in whole of this code  
//  is strictly prohibited. Violators WILL be prosecuted to the      
//  maximum extent allowed by law.                                   
//                                                                   
//-------------------------------------------------------------------


class CBackgroundModel
{
  String MeshFile  = "Models/Background.ms2";
  String SkinClass = "CBackgroundModelSkin";
  Array  Animation = [];
}

class CBackgroundModelSkin
{
  Array Materials = [
      new CModelMaterial(
        "0", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "DISABLE", // alpha mode
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(0.000000, 0.000000, 0.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false // double sided
      )
    ];
}
