//-------------------------------------------------------------------
//
//  This code is copyright 2001 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//  Redux Model Header Update
//-------------------------------------------------------------------


class Chum_SovietSoldierRifleModel extends CBaseModel
{

  static int     InstancesQty         = CBaseModel::DefaultInstancesQty;

  static int     ShadowCheckMode      = CBaseModel::DefaultShadowCheckMode;

  static boolean PlanarShadow         = CBaseModel::DefaultPlanarShadow;

  static float   PlanarShadowLodShift = CBaseModel::DefaultPlanarShadowLodShift; 

  static boolean FakeShadow           = CBaseModel::DefaultFakeShadow;

  static float   FakeShadowScale      = CBaseModel::DefaultFakeShadowScale;

  static float   LodForShadowChange   = CBaseModel::DefaultLodForShadowChange;

  static float   LodForShadowHide      = CBaseModel::DefaultLodForShadowHide;
  
  static boolean UseBoxForIsection    = CBaseModel::DefaultUseBoxForIsection;
  
  static boolean UseShapesAsWalkedMesh = CBaseModel::DefaultUseShapesAsWalkedMesh; //redux missin
  
  

  String     MeshFile        = "Models/hum_SovietSoldierRifle.ms2";
  String     SkinClass       = "Chum_SovietSoldierRifleModelSkin";

  String     RouterMapFile   = "Models/hum_SovietSoldierRifle.rmap";

  Array  Animation = [];

  Map    ConfigSets = new Map([
      [ "lo_Bind", [ "l_Arm_Left", "l_Arm_Right", "l_Bedro_Left", "l_Bedro_Right", "l_Elbow_Left", "l_Elbow_Right", "l_Foot_Left", "l_Foot_Right", "l_Golen_Left", "l_Golen_Right", "l_Hand_Left", "l_Hand_Right", "l_Head", "l_Hips", "l_Shoulder_Left", "l_Shoulder_Right", "l_Spine", "l_Spine1" ] ],
      [ "lo_Weapon_Bind", [ "l_Weapon" ] ]
    ]);

  Map    MaterialsNameId = new Map([
      [ "lambert1", "0"],
      [ "G5EngineShader1", "1"]
    ]);
}

class Chum_SovietSoldierRifleModelSkin
{
  Array Materials = [
      new CModelMaterial(
        "0", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(0.400000, 0.400000, 0.400000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Body, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "1", // material id
        "Textures/hum_Soviet_Soldier.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Body, // substance type
        "" // envmap name
      )
    ];
}
