//-------------------------------------------------------------------
//                                                                   
//  This code is copyright 2001 by G5 Software.                      
//  Any unauthorized usage, either in part or in whole of this code  
//  is strictly prohibited. Violators WILL be prosecuted to the      
//  maximum extent allowed by law.                                   
//  Redux Model Header Update                                                                 
//-------------------------------------------------------------------


class Chum_SovietTankmanModel extends CBaseModel
{

   static int     InstancesQty         = CBaseModel::DefaultInstancesQty;

  static int     ShadowCheckMode      = CBaseModel::DefaultShadowCheckMode;

  static boolean PlanarShadow         = CBaseModel::DefaultPlanarShadow;

  static float   PlanarShadowLodShift = CBaseModel::DefaultPlanarShadowLodShift; 

  static boolean FakeShadow           = CBaseModel::DefaultFakeShadow;

  static float   FakeShadowScale      = CBaseModel::DefaultFakeShadowScale;

  static float   LodForShadowChange   = CBaseModel::DefaultLodForShadowChange;

  static float   LodForShadowHide      = CBaseModel::DefaultLodForShadowHide;
  
  static boolean UseBoxForIsection    = CBaseModel::DefaultUseBoxForIsection;
  
  static boolean UseShapesAsWalkedMesh = CBaseModel::DefaultUseShapesAsWalkedMesh; //redux missin

  String     MeshFile        = "Models/hum_SovietTankman.ms2";
  String     SkinClass       = "Chum_SovietTankmanModelSkin";

  String     RouterMapFile   = "Models/hum_SovietTankman.rmap";

  Array  Animation = [];
}

class Chum_SovietTankmanModelSkin
{
  Array Materials = [
      new CModelMaterial(
        "0", // material id
        "Textures/KARO2.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(0.800000, 0.800000, 0.800000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Body, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "1", // material id
        "Textures/hum_Soviet_Tankman.tex", // texture name
        "Textures/hum_AmericanSoldier_b.tex", // bump tex name
        "", // micro tex name
        "Textures/hum_AmericanSoldier_b.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(1.000000, 1.000000, 1.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Body, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "2", // material id
        "Textures/hum_Soviet_Tankman.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(0.800000, 0.800000, 0.800000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.300000, 0.300000, 0.300000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Body, // substance type
        "" // envmap name
      )
    ];
}
