//-------------------------------------------------------------------
//                                                                   
//  This code is copyright 2001 by G5 Software.                      
//  Any unauthorized usage, either in part or in whole of this code  
//  is strictly prohibited. Violators WILL be prosecuted to the      
//  maximum extent allowed by law.                                   
//  Redux Model Header Update                                                             
//-------------------------------------------------------------------


class Cu_air_IL2MModel extends CBaseModel
{

   static int     InstancesQty         = CBaseModel::DefaultInstancesQty;

  static int     ShadowCheckMode      = CBaseModel::DefaultShadowCheckMode;

  static boolean PlanarShadow         = CBaseModel::DefaultPlanarShadow;

  static float   PlanarShadowLodShift = CBaseModel::DefaultPlanarShadowLodShift; 

  static boolean FakeShadow           = CBaseModel::DefaultFakeShadow;

  static float   FakeShadowScale      = CBaseModel::DefaultFakeShadowScale;

  static float   LodForShadowChange   = CBaseModel::DefaultLodForShadowChange;

  static float   LodForShadowHide      = CBaseModel::DefaultLodForShadowHide;
  
  static boolean UseBoxForIsection    = CBaseModel::DefaultUseBoxForIsection;
  
  static boolean UseShapesAsWalkedMesh = CBaseModel::DefaultUseShapesAsWalkedMesh; //redux missin
  
  String     MeshFile        = "Models/u_air_IL2M.ms2";
  String     SkinClass       = "Cu_air_IL2MModelSkin";

  String     RouterMapFile   = "Models/u_air_IL2M.rmap";

  Array  Animation = [
      ["prop_rotate", ["Rotor", 0, 3]]
    ];

  Map    ConfigSets = new Map([]);

  Map    MaterialsNameId = new Map([
      [ "G5EngineShader2", "0"],
      [ "G5EngineShader1", "1"]
    ]);
}

class Cu_air_IL2MModelSkin
{
  Array Materials = [
      new CModelMaterial(
        "0", // material id
        "Textures/u_air_rotors.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "NORMAL", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "1", // material id
        "Textures/u_air_IL2M.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      )
    ];
}
