//-------------------------------------------------------------------
//                                                                   
//  This code is copyright 2001 by G5 Software.                      
//  Any unauthorized usage, either in part or in whole of this code  
//  is strictly prohibited. Violators WILL be prosecuted to the      
//  maximum extent allowed by law.                                   
//                                                                   
//-------------------------------------------------------------------


class Cu_veh_t34_85_44_2Model extends CBaseModel
{

  static int     InstancesQty         = CBaseModel::DefaultInstancesQty;

  static int     ShadowCheckMode      = CBaseModel::DefaultShadowCheckMode;

  static boolean PlanarShadow         = CBaseModel::DefaultPlanarShadow;

  static float   PlanarShadowLodShift = CBaseModel::DefaultPlanarShadowLodShift;

  static boolean UseBoxForIsection    = CBaseModel::DefaultUseBoxForIsection;

  static boolean FakeShadow           = CBaseModel::DefaultFakeShadow;

  static float   FakeShadowScale      = CBaseModel::DefaultFakeShadowScale;

  static float   LodForShadowChange   = CBaseModel::DefaultLodForShadowChange;
  String     MeshFile        = "Models/u_veh_t34_85_44_2.ms2";
  String     SkinClass       = "Cu_veh_t34_85_44_2ModelSkin";

  String     RouterMapFile   = "Models/u_veh_t34_85_44_2.rmap";

  Array  Animation = [
      ["L_Wheel01_lift", ["joint_WheelLeftMain1", 0, 2]],
      ["L_Wheel02_lift", ["joint_WheelLeftMain2", 0, 2]],
      ["L_Wheel03_lift", ["joint_WheelLeftMain3", 0, 2]],
      ["L_Wheel04_lift", ["joint_WheelLeftMain4", 0, 2]],
      ["L_Wheel05_lift", ["joint_WheelLeftMain5", 0, 2]],
      ["R_Wheel01_lift", ["joint_WheelRightMain1", 0, 2]],
      ["R_Wheel02_lift", ["joint_WheelRightMain2", 0, 2]],
      ["R_Wheel03_lift", ["joint_WheelRightMain3", 0, 2]],
      ["R_Wheel04_lift", ["joint_WheelRightMain4", 0, 2]],
      ["R_Wheel05_lift", ["joint_WheelRightMain5", 0, 2]],
      ["body_recoil_bf", ["Body", 10, 20]],
      ["body_recoil_fb", ["Body", 0, 10]],
      ["body_recoil_lr", ["Body", 20, 30]],
      ["body_recoil_rl", ["Body", 30, 40]],
      ["gun_a", ["Weapon_B", 0, 1]],
      ["gun_a_recoil", ["Weapon_A", 0, 30]],
      ["gun_c_leftdn", ["Weapon_C", 4, 5]],
      ["gun_c_leftup", ["Weapon_C", 2, 3]],
      ["gun_c_rightdn", ["Weapon_C", 6, 7]],
      ["gun_c_rightup", ["Weapon_C", 0, 1]],
      ["luk_body_driver", ["driver_l_Arm_Left", 0, 20], ["driver_l_Arm_Right", 0, 20], ["driver_l_Elbow_Left", 0, 20], ["driver_l_Elbow_Right", 0, 20], ["driver_l_Hand_Left", 0, 20], ["driver_l_Hand_Right", 0, 20], ["driver_l_Head", 0, 20], ["driver_l_Head2", 0, 20], ["driver_l_Hips", 0, 20], ["driver_l_Shoulder_Left", 0, 20], ["driver_l_Shoulder_Right", 0, 20], ["driver_l_Spine", 0, 20], ["driver_l_Spine1", 0, 20], ["driver_l_Weapon", 0, 20]],
      ["luk_body_open", ["Luk_A", 0, 1]],
      ["luk_main_commander", ["l_Arm_Left", 0, 30], ["l_Arm_Right", 0, 30], ["l_Elbow_Left", 0, 30], ["l_Elbow_Right", 0, 30], ["l_Hand_Left", 0, 30], ["l_Hand_Right", 0, 30], ["l_Head", 0, 30], ["l_Head2", 0, 30], ["l_Hips", 0, 30], ["l_Shoulder_Left", 0, 30], ["l_Shoulder_Right", 0, 30], ["l_Spine", 0, 30], ["l_Spine1", 0, 30], ["l_Weapon", 0, 30]],
      ["luk_main_open", ["Luk_C", 0, 1], ["Luk_D", 0, 1]],
      ["luk_right_open", ["Luk_B", 0, 1]],
      ["turret_a", ["Turret_A", 0, 4]],
      ["turret_out1", ["Turret_A_explode", 0, 50]],
      ["turret_out2", ["Turret_A_explode", 61, 71]],
      ["wheels_left", ["WheelLeftFront", 0, 60], ["WheelLeftMain1", 0, 60], ["WheelLeftMain2", 0, 60], ["WheelLeftMain3", 0, 60], ["WheelLeftMain4", 0, 60], ["WheelLeftMain5", 0, 60], ["WheelLeftRear", 0, 60]],
      ["wheels_right", ["WheelRightFront", 0, 60], ["WheelRightMain1", 0, 60], ["WheelRightMain2", 0, 60], ["WheelRightMain3", 0, 60], ["WheelRightMain4", 0, 60], ["WheelRightMain5", 0, 60], ["WheelRightRear", 0, 60]]
    ];

  Map    ConfigSets = new Map([
      [ "Body_CrashedSet", [ "Body_Crashed" ] ],
      [ "Body_NormalSet", [ "Body", "Body_2", "Body_driver", "HullDriver", "HullEngine", "HullGunlayer", "Luk_A", "Weapon_C" ] ],
      [ "TrackLeft_CrashedSet", [ "TrackLeft_Crashed" ] ],
      [ "TrackLeft_NormalSet", [ "GearL", "TrackLeft" ] ],
      [ "TrackRight_CrashedSet", [ "TrackRight_Crashed" ] ],
      [ "TrackRight_NormalSet", [ "GearR", "TrackRight" ] ],
      [ "Turret_A_CrashedSet", [ "Turret_A_Crashed" ] ],
      [ "Turret_A_NormalSet", [ "Body_commander", "Luk_B", "Luk_C", "Luk_D", "Numbers", "Turret_A", "Weapon_A", "Weapon_B" ] ],
      [ "modelPanel4ViewSelectedSet", [ "Body_driver", "Body_driver_LOD1", "driver_l_Hips" ] ],
      [ "modelPanel4ViewSelectedSet1", [ "driver_l_Hips" ] ]
    ]);

  Map    MaterialsNameId = new Map([
      [ "Body_Normal", "0"],
      [ "Body_Normal2", "1"],
      [ "Turret_CrashedMaterial", "2"],
      [ "Body_CrashedMaterial", "3"],
      [ "ArmourHullTOP", "4"],
      [ "ArmourHullRIGHT", "5"],
      [ "ArmourHullLEFT", "6"],
      [ "ArmourHullBOTTOM", "7"],
      [ "ArmourHullREAR", "8"],
      [ "ArmourHullFWD", "9"],
      [ "DriverCM", "10"],
      [ "ArmourTurretTOP", "11"],
      [ "ArmourTurretFWD", "12"],
      [ "ArmourTurretREAR", "13"],
      [ "ArmourTurretRIGHT", "14"],
      [ "ArmourTurretLEFT", "15"],
      [ "NumberMaterial", "16"],
      [ "Track_rightNormal", "17"],
      [ "TrackCrashedMaterial", "18"],
      [ "_Crashed_CM_MAterial", "19"],
      [ "LeftTrack_Normal", "20"],
      [ "export_ani_lambert2", "21"]
    ]);
}

class Cu_veh_t34_85_44_2ModelSkin
{
  Array Materials = [
      new CModelMaterial(
        "0", // material id
        "Textures/u_veh_t34_85.tex", // texture name
        "Textures/u_veh_t34_85_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_85_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        30.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "1", // material id
        "Textures/u_veh_t34_85_turret.tex", // texture name
        "Textures/u_veh_t34_85_turret_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_85_turret_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        30.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "2", // material id
        "Textures/u_veh_t34_85_turret_Crashed.tex", // texture name
        "Textures/u_veh_t34_85_turret_Crashed_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_85_turret_Crashed_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        20.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "3", // material id
        "Textures/u_veh_t34_85_Crashed.tex", // texture name
        "Textures/u_veh_t34_85_Crashed_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_85_Crashed_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        20.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "4", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourHullTOP, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "5", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourHullRIGHT, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "6", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourHullLEFT, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "7", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourHullBOTTOM, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "8", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourHullREAR, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "9", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourHullFWD, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "10", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Body, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "11", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourTurretTOP, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "12", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourTurretFWD, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "13", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourTurretREAR, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "14", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourTurretRIGHT, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "15", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_ArmourTurretLEFT, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "16", // material id
        "Textures/Number_00.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "KEYCOLOR", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "17", // material id
        "Textures/u_veh_t34_track550.tex", // texture name
        "Textures/u_veh_t34_track550_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_track550_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        30.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "18", // material id
        "Textures/u_veh_t34_track550_Crashed.tex", // texture name
        "Textures/u_veh_t34_track550_Crashed_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_track550_Crashed_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        20.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "19", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "20", // material id
        "Textures/u_veh_t34_track550.tex", // texture name
        "Textures/u_veh_t34_track550_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_t34_track550_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        30.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "21", // material id
        "Textures/hum_Soviet_Tankman.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(0.800000, 0.800000, 0.800000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "FakeShadow", // material id
        "Textures/BottomShadow.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "NORMAL", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      )
    ];
}
