//-------------------------------------------------------------------
//                                                                   
//  This code is copyright 2001 by G5 Software.                      
//  Any unauthorized usage, either in part or in whole of this code  
//  is strictly prohibited. Violators WILL be prosecuted to the      
//  maximum extent allowed by law.                                   
//                                                                   
//-------------------------------------------------------------------


class Cu_veh_zis5Model extends CBaseModel
{

  static int     InstancesQty         = CBaseModel::DefaultInstancesQty;

  static int     ShadowCheckMode      = CBaseModel::DefaultShadowCheckMode;

  static boolean PlanarShadow         = CBaseModel::DefaultPlanarShadow;

  static float   PlanarShadowLodShift = CBaseModel::DefaultPlanarShadowLodShift; 

  static boolean FakeShadow           = CBaseModel::DefaultFakeShadow;

  static float   FakeShadowScale      = CBaseModel::DefaultFakeShadowScale;

  static float   LodForShadowChange   = CBaseModel::DefaultLodForShadowChange;

  static float   LodForShadowHide      = CBaseModel::DefaultLodForShadowHide;
  
  static boolean UseBoxForIsection    = CBaseModel::DefaultUseBoxForIsection;
  
  static boolean UseShapesAsWalkedMesh = CBaseModel::DefaultUseShapesAsWalkedMesh; //redux missin
  
  String     MeshFile        = "Models/u_veh_zis5.ms2";
  String     SkinClass       = "Cu_veh_zis5ModelSkin";

  String     RouterMapFile   = "Models/u_veh_zis5.rmap";

  Array  Animation = [
      ["DriverAnim", ["Driver", 0, 1]],
      ["bort_open", ["Bort", 0, 2]],
      ["l_door_open", ["DoorLeft", 0, 1]],
      ["r_door_open", ["DoorRight", 0, 1]],
      ["wheels_rotate", ["TrackLeft", 0, 3], ["TrackRight", 0, 3], ["Wheel_FL", 0, 3], ["Wheel_FR", 0, 3]],
      ["wheels_turn", ["Shkvoren_L", 0, 2], ["Shkvoren_R", 0, 2]]
    ];

  Map    ConfigSets = new Map([
      [ "Body_CrashedSet", [ "Body_Crashed" ] ],
      [ "Body_NormalSet", [ "Body", "Body_attach", "DoorLeftGlass", "DoorRightGlass" ] ],
      [ "Damaged_CrashedSet", [ "Damaged_Crashed" ] ],
      [ "Damaged_NormalSet", [ "Bort", "Damaged" ] ],
      [ "Driver_CrashedSet", [ "Dead_Driver" ] ],
      [ "Driver_NormalSet", [ "Driver" ] ],
      [ "TrackLeft_CrashedSet", [ "TrackLeft_Crashed" ] ],
      [ "TrackLeft_NormalSet", [ "TrackLeft" ] ],
      [ "TrackRight_CrashedSet", [ "TrackRight_Crashed" ] ],
      [ "TrackRight_NormalSet", [ "TrackRight" ] ]
    ]);

  Map    MaterialsNameId = new Map([
      [ "Body_NormalMAterial", "0"],
      [ "Glass_NormalMaterial", "1"],
      [ "Body_crashed_Material", "2"],
      [ "Glass_CrashedMaterial", "3"],
      [ "DAMAGEDShader", "4"],
      [ "hum_SovietSoldierRifle26_G5EngineShader1", "5"],
      [ "Metal", "6"]
    ]);
}

class Cu_veh_zis5ModelSkin
{
  Array Materials = [
      new CModelMaterial(
        "0", // material id
        "Textures/u_veh_Zis5.tex", // texture name
        "Textures/u_veh_Zis5_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_Zis5_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        30.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "1", // material id
        "Textures/u_veh_Zis5_glass.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "NORMAL", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Glass, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "2", // material id
        "Textures/u_veh_Zis5_Crashed.tex", // texture name
        "Textures/u_veh_Zis5_Crashed_h.tex", // bump tex name
        "", // micro tex name
        "Textures/u_veh_Zis5_Crashed_h.tex", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.300000, 0.300000, 0.300000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        20.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "3", // material id
        "Textures/u_veh_Zis5_glass_Crashed.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "NORMAL", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Glass, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "4", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Wood, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "5", // material id
        "Textures/hum_Soviet_Soldier.tex", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Default, // substance type
        "" // envmap name
      ),
      new CModelMaterial(
        "6", // material id
        "", // texture name
        "", // bump tex name
        "", // micro tex name
        "", // specular tex name
        "", // emissive tex name
        "", // light tex name
        "", // height tex name
        "DISABLE", // alpha mode
        LMDL_Default, // lighting model
        1.000000, // micro tex tiling U
        1.000000, // micro tex tiling V
        1.000000, // bump tex tiling U
        1.000000, // bump tex tiling V
        new Color(0.000000, 0.000000, 0.000000), // ambient
        new Color(1.000000, 1.000000, 1.000000, 1.000000), // diffuse
        new Color(0.000000, 0.000000, 0.000000), // specular
        new Color(0.000000, 0.000000, 0.000000), // emissive
        0.000000, // power
        false, // double sided
        0.000000, // glossiness
        1.000000, // fresnel
        1.000000, // parallax
        CMaterialStructure::MSID_Metal, // substance type
        "" // envmap name
      )
    ];
}
