//-------------------------------------------------------------------
//
//  This code is copyright 2001 by G5 Software.
//  Any unauthorized usage, either in part or in whole of this code
//  is strictly prohibited. Violators WILL be prosecuted to the
//  maximum extent allowed by law.
//
//-------------------------------------------------------------------

class BerezovWorldMatrices extends CWorldMatrices
{
  final static float MatrixWidth  = 18000.0;
  final static float MatrixHeight = 18000.0;
}


class BerezovLandscapeLayer extends CLandscapeLayer
{
  final static int     ImageWidth              = 2049;
  final static int     ImageHeight             = 2049;

  final static String ImageFileName           = "Missions/MyMission/Berezov/hmap.raw";

  final static float  FloatValueFactor        = 0.070000*257.0;

}

class BerezovWaterHeights extends CBaseWaterHeightsLayer
{
  final static String ImageFileName           = "Missions/MyMission/Berezov/hwater.raw";

  final static float  FloatValueFactor        = 0.070000*257.0;
}

class BerezovTerrainZoneLayer extends CTerrainZoneLayer, CBaseZoneMap
{
  final static int     ImageWidth              = 1024;
  final static int     ImageHeight             = 1024;

  final static String ImageFileName           = "Missions/MyMission/Berezov/TerrainZone_Test.bmp";
}

class BerezovRouterZoneLayer extends CTerrainZoneLayer, CBaseZoneMap
{
  final static int     ImageWidth              = 2048;
  final static int     ImageHeight             = 2048;

  final static String ImageFileName           = "Missions/MyMission/Berezov/RouterZone_Test.bmp";
}


class BerezovMicroTextures1 extends CMicroTexLayer
{
  final static String ImageFileName           = "Missions/MyMission/Berezov/micro_Test.bmp";
}
